version: "3.8"
services:
  database:
    container_name: "psql"
    build: ./database
    env_file:
      - ./database/database.env
    ports:
      - 5432:5432
    networks:
      - plantager-network
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    #   - ./data/:/var/lib/postgresql/data/
  rabbitmq:
    image: "rabbitmq:3"
    ports:
      - "5672:5672"
    networks:
      - plantager-network

networks:
  plantager-network:
    external: true
